---
title: "git_01"
author: "Destiny Maldonado"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

ALL in the golden afternoon.   
Full leisurely we glide;  
For both our oars, with little skill,  
By little arms are plied,  
While little hands make vain pretence.  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Something there is that doesn't love a wall,  
That sends the frozen-ground-swell under it,  
And spills the upper boulders in the sun;  
And makes gaps even two can pass abreast.  
The work of hunters is another thing:  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make.  
      The billows smooth and bright —  
And this was odd, because it was.  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun.  
Had got no business to be there.  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

I heard a Fly buzz - when I died -  
The Stillness in the Room.  
Was like the Stillness in the Air -  
Between the Heaves of Storm -  

The Eyes around - had wrung them dry -  
And Breaths were gathering firm.  
For that last Onset - when the King.  
Be witnessed - in the Room -  

I willed my Keepsakes - Signed away.  
What portion of me be.  
Assignable - and then it was.  
There interposed a Fly -  

